In [1]:
import numpy as np
a = np.random.randint(1,51,size=(5,4))
a 

array([[30, 14,  5,  6],
       [ 9, 29, 25, 50],
       [30,  1, 26,  7],
       [33,  8,  1, 44],
       [ 2, 25, 19, 50]])

In [2]:
def anti_diag(arr):
    ans = np.array([])
    i=0
    while i < min(arr.shape):
        ans = np.concatenate((ans,arr[i,-(i+1)]),axis=None)
        i+=1
    return ans

anti_diag(a)

array([ 6., 25.,  1., 33.])

In [3]:
b = a[a<a.mean()]
b 

array([14,  5,  6,  9,  1,  7,  8,  1,  2, 19])

In [4]:
def numpy_boundary_traversal(matrix):
    r, c = matrix.shape
    top = matrix[0, :]
    right = matrix[1:r, -1]
    bottom = matrix[-1, -2::-1] if r > 1 else []
    left = matrix[r-2:0:-1, 0] if c > 1 else []
    return list(np.concatenate((top, right, bottom, left)))
numpy_boundary_traversal(a)


[30, 14, 5, 6, 50, 7, 44, 50, 19, 25, 2, 33, 30, 9]