In [1]:
import numpy as np

In [2]:
a = np.random.uniform(1,10,20)
a = np.round(a,2)
a

array([4.1 , 2.31, 9.2 , 6.32, 6.23, 9.84, 7.86, 8.33, 9.85, 9.15, 1.32,
       9.71, 9.78, 5.9 , 1.83, 2.91, 5.2 , 9.56, 5.06, 4.1 ])

In [3]:
print(f'min of array: {a.min()}\nmax of array: {a.max()}\nmedian of array: {np.median(a).round(2)}')

min of array: 1.32
max of array: 9.85
median of array: 6.28


In [4]:
a = np.where(a<5,a**2,a)
a= a.round(2)
a 

array([16.81,  5.34,  9.2 ,  6.32,  6.23,  9.84,  7.86,  8.33,  9.85,
        9.15,  1.74,  9.71,  9.78,  5.9 ,  3.35,  8.47,  5.2 ,  9.56,
        5.06, 16.81])

In [5]:
def numpy_alternate_sort(array):
    sorted_arr = np.sort(array)
    result = []
    i, j = 0, len(sorted_arr) - 1
    while i <= j:
        result.append(sorted_arr[i])
        if i != j:
            result.append(sorted_arr[j])
        i += 1
        j -= 1
    return np.array(result)
numpy_alternate_sort(a)

array([ 1.74, 16.81,  3.35, 16.81,  5.06,  9.85,  5.2 ,  9.84,  5.34,
        9.78,  5.9 ,  9.71,  6.23,  9.56,  6.32,  9.2 ,  7.86,  9.15,
        8.33,  8.47])